#ifndef SPINDULYS_CPU_H
#define SPINDULYS_CPU_H

#include <spindulys.h>


#if SPINDULYS_USE_NAMESPACES

#define CPU_NAMESPACE_OPEN_SCOPE SPINDULYS_NAMESPACE_OPEN_SCOPE SPINDULYS_BASE_NAMESPACE_OPEN_SCOPE SPINDULYS_CPU_NAMESPACE_OPEN_SCOPE
#define CPU_NAMESPACE_CLOSE_SCOPE SPINDULYS_NAMESPACE_CLOSE_SCOPE SPINDULYS_BASE_NAMESPACE_CLOSE_SCOPE SPINDULYS_CPU_NAMESPACE_CLOSE_SCOPE

#else

#define CPU_NAMESPACE_OPEN_SCOPE 
#define CPU_NAMESPACE_CLOSE_SCOPE 

#endif // SPINDULYS_USE_NAMESPACE

// Set to 0 to disable CPU tracing.
#define CPU_TRACING 0
#if CPU_TRACING
#define CPU_TRACE() MTR_SCOPE("CPU", __func__);
#define CPU_SCOPE(m) MTR_SCOPE("CPU", m);
#define CPU_BEGIN(m) MTR_BEGIN("CPU", m);
#define CPU_END(m) MTR_END("CPU", m);
#else
#define CPU_TRACE()
#define CPU_SCOPE(m)
#define CPU_BEGIN(m)
#define CPU_END(m)
#endif // TRACING

#endif //SPINDULYS_CPU_H
