#ifndef SPINDULYS_FRONTEND_H
#define SPINDULYS_FRONTEND_H

#include <spindulys.h>


#if SPINDULYS_USE_NAMESPACES

#define FRONTEND_NAMESPACE_OPEN_SCOPE SPINDULYS_NAMESPACE_OPEN_SCOPE SPINDULYS_FRONTEND_NAMESPACE_OPEN_SCOPE
#define FRONTEND_NAMESPACE_CLOSE_SCOPE SPINDULYS_NAMESPACE_CLOSE_SCOPE SPINDULYS_FRONTEND_NAMESPACE_CLOSE_SCOPE

#else

#define FRONTEND_NAMESPACE_OPEN_SCOPE 
#define FRONTEND_NAMESPACE_CLOSE_SCOPE 

#endif // SPINDULYS_USE_NAMESPACE

// Set to 0 to disable FRONTEND tracing.
#define FRONTEND_TRACING 0
#if FRONTEND_TRACING
#define FRONTEND_TRACE() MTR_SCOPE("FRONTEND", __func__);
#define FRONTEND_SCOPE(m) MTR_SCOPE("FRONTEND", m);
#define FRONTEND_BEGIN(m) MTR_BEGIN("FRONTEND", m);
#define FRONTEND_END(m) MTR_END("FRONTEND", m);
#else
#define FRONTEND_TRACE()
#define FRONTEND_SCOPE(m)
#define FRONTEND_BEGIN(m)
#define FRONTEND_END(m)
#endif // FRONTEND_TRACING

#endif //SPINDULYS_FRONTEND_H
