#ifndef SPINDULYS_SAMPLER_STRATIFIED_H
#define SPINDULYS_SAMPLER_STRATIFIED_H

#include "sampler.h"

#include "../math/vec3.h"

#include "../../spindulys.h"


SPINDULYS_NAMESPACE_OPEN_SCOPE


SPINDULYS_NAMESPACE_CLOSE_SCOPE

#endif // SPINDULYS_SAMPLER_STRATIFIED_H
